### ISSUE TITLE
create a Windows and non-Windows artifact/zip file

### ISSUE THREAD

**Issue by Mo-Gul** [imaandrew/caskaydia-cove#1]
It would be great if you could create two artifacts/zip files. One with with "Windows Compatible" files and one without.

I tried to patch the `main.yml` file, but have no clue about GitHub Actions. Thus I can only suggest to change

https://github.com/imaandrew/caskaydia-cove/blob/f6fc1d6e2660e17a673679c7a2cb27a01e4fe5a6/.github/workflows/main.yml#L27

to e.g.

```
          zip -m CaskaydiaCove_Windows.zip "patched-fonts/*Windows Compatible.ttf"
          zip -m CaskaydiaCove.zip "patched-fonts/*.ttf"
```

to create the ZIP files. But I don't have a clue what changes are needed to

https://github.com/imaandrew/caskaydia-cove/blob/f6fc1d6e2660e17a673679c7a2cb27a01e4fe5a6/.github/workflows/main.yml#L36-L43

**Comment by imaandrew** [comment]
Yeah that should be an easy change. I haven't looked at the build system for a while so it could probably use some updating. I'll be sure to work on it later this week when I'm less busy.

**Comment by Mo-Gul** [comment]
Awesome. The feature implemented in https://github.com/imaandrew/caskaydia-cove/commit/1aeae9e91ea2e26df5f0d7fa4dbd82b38078461b seems to address this feature request.

I downloaded the Windows version of the latest release [v2110.31](https://github.com/imaandrew/caskaydia-cove/releases/tag/v2110.31) and the ZIP looks fine.

Thank you very much for the implementation!!!
