### ISSUE TITLE
reenable `Patch Fonts` workflow

### ISSUE THREAD

**Issue by Mo-Gul** [imaandrew/caskaydia-cove#3]
the `Patch Fonts` workflow seems to be disabled. It shows the message:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

Could you reenable it, please!?

**Comment by Mo-Gul** [comment]
As I have just seen, it seems that Nerd Fonts does release the `Caskaydia Cove Nerd Font` themself since v2.1.0.

See [Nerd Fonts Release Changelog](https://www.nerdfonts.com/releases) and the assets of [Nerd Fonts Releases](https://github.com/ryanoasis/nerd-fonts/releases) (that would be <https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/CascadiaCode.zip> for the current latest release).

So maybe this repository is obsolete in the meantime!? What do you think?

**Comment by Mo-Gul** [comment]
Maybe it is not obsolete, because of https://github.com/ryanoasis/nerd-fonts/issues/785#issuecomment-1278433467, that is, this repo creates TTF fonts while the Nerd Font repo releases OTF fonts.

**Comment by imaandrew** [comment]
I did some searching and i found that https://github.com/adam7/delugia-code is a thing. It works fine for all my use cases and they do release TTF fonts. Give it a try and see if it works for you. If it does, I think this repository can be archived.

**Comment by Mo-Gul** [comment]
I can confirm that the font `Delugia` (in the `delugia-complete.zip` resource) works like the font `CaskaydiaCove NF` from this repository. So I am fine with archiving this repository.

Many thanks for your research and your efforts. It was a pleasure!

**Comment by Mo-Gul** [comment]
Before archiving maybe you should edit the README accordingly and point to the Delugia repository, so others benefit from your research as well.
